version: '3'
services:
  mysql:
    image: mysql
    env_file: ./mysql/.env_sample
    volumes: # 上の階層で指定した db_data を使いますよ
       - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    depends_on:
      - django

  django:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    tty: true

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
volumes:
  est-data:
  db_data:
