# Generated by Django 2.2.10 on 2020-05-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='bool_takeout',
            field=models.BooleanField(default=1, verbose_name='テイクアウトOK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant_posts'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_range',
            field=models.IntegerField(blank=True, choices=[(1, '~500'), (2, '~1000'), (3, '~2000')], null=True, verbose_name='予算'),
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant_memo',
            field=models.TextField(blank=True, null=True, verbose_name='レストランのここがいい！'),
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='レストラン名'),
        ),
        migrations.AddField(
            model_name='item',
            name='ward_address',
            field=models.CharField(blank=True, choices=[('千代田区', '千代田区'), ('中央区', '中央区'), ('港区', '港区'), ('新宿区', '新宿区'), ('文京区', '文京区'), ('台東区', '台東区'), ('墨田区', '墨田区'), ('江東区', '江東区'), ('品川区', '品川区'), ('目黒区', '目黒区'), ('大田区', '大田区'), ('世田谷区', '世田谷区'), ('渋谷区', '渋谷区'), ('中野区', '中野区'), ('杉並区', '杉並区'), ('豊島区', '豊島区'), ('北区', '北区'), ('荒川区', '荒川区'), ('板橋区', '板橋区'), ('練馬区', '練馬区'), ('足立区', '足立区'), ('葛飾区', '葛飾区'), ('江戸川区', '江戸川区')], max_length=20, null=True, verbose_name='住所（区）'),
        ),
    ]
