# Generated by Django 2.2.10 on 2020-05-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200527_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bool_takeout',
        ),
    ]
