# Generated by Django 2.1.15 on 2020-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_item_bool_takeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/images/unnamed.jpg', upload_to='images/restaurant_posts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_memo',
            field=models.TextField(blank=True, help_text='もっと詳しく聞かせて...（写真も忘れずにね）', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(blank=True, help_text='タイトルはズバリ...！', max_length=20, null=True, verbose_name=''),
        ),
    ]
