# Generated by Django 3.0.8 on 2020-08-05 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200719_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant_posts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_memo',
            field=models.TextField(blank=True, help_text='感想・作り方（写真も忘れずにね！）', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(blank=True, help_text='料理名', max_length=20, null=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('commented_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Item')),
            ],
        ),
    ]
