# Generated by Django 3.1 on 2020-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200719_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant_posts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_memo',
            field=models.TextField(blank=True, help_text='感想・作り方（写真も忘れずにね！）', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(blank=True, help_text='料理名', max_length=20, null=True, verbose_name=''),
        ),
    ]
