# Generated by Django 3.1 on 2020-08-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200828_1501'),
        ('app', '0006_auto_20200807_2109'),
    ]

    operations = [
    ]
