# Generated by Django 3.1 on 2020-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200902_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_memo',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=''),
        ),
    ]
