# Generated by Django 3.1 on 2020-09-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
